### ISSUE TITLE
Start commisioner fails

### ISSUE THREAD

**Issue by jobroe** [openthread/borderrouter#129]
I 'm using 3 x efr32's  ( 2 FTD's flashed with ot-cli-ftd and 1 NCP with ot-ncp-ftd) and a RPI 3B as OTBR to setup a example thread network. 
 To form a thread network I used the Web interface and it seems to work:
```
sudo wpanctl status
wpan0 => [
        "NCP:State" => "associated"
        "Daemon:Enabled" => true
        "NCP:Version" => "OPENTHREAD/20170716-00333-g197e0c1f-dirty; EFR32; Jan 16 2018 21:51:48"
        "Daemon:Version" => "0.08.00d (/2e4e056; Jan  9 2018 20:46:52)"
        "Config:NCP:DriverName" => "spinel"
        "NCP:HardwareAddress" => [000B57FFFEB393DF]
        "NCP:Channel" => 15
        "Network:NodeType" => "leader"
        "Network:Name" => "OpenThreadDemo"
        "Network:XPANID" => 0x1111111122222222
        "Network:PANID" => 0x1234
        "IPv6:MeshLocalAddress" => "fd11:1111:1122:0:e05a:80c:d639:c7ef"
        "IPv6:MeshLocalPrefix" => "fd11:1111:1122::/64"
        "com.nestlabs.internal:Network:AllowingJoin" => false
]
```
Then I tried to start the commissioner and it fails with the error:

```
sudo wpanctl commissioner -e
commissioner failed with error 16. PropertyNotFound
```
See also:

```

sudo systemctl status wpantund.service
● wpantund.service - wpantund
   Loaded: loaded (/etc/systemd/system/wpantund.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-01-16 20:59:56 UTC; 22h ago
 Main PID: 428 (wpantund)
   CGroup: /system.slice/wpantund.service
           └─428 /usr/sbin/wpantund -o Daemon:SetDefaultRouteForAutoAddedPrefix true -o IPv6:SetSLAACForAutoAddedPrefix true

Jan 17 19:22:14 raspberrypi wpantund[428]: Pushing a new SLAAC address fd11:22::6878:17c8:b347:22e2/64 to NCP
Jan 17 19:22:14 raspberrypi wpantund[428]: Adding address "fd11:22::6878:17c8:b347:22e2/64" to NCP
Jan 17 19:30:52 raspberrypi wpantund[428]: wpantund[428]: SpinelNCPTaskSendCommand.cpp:322: Requirement Failed ((mRetVal) == 0)
Jan 17 19:30:52 raspberrypi wpantund[428]: wpantund[428]: SendCommand task encountered an error: 16 (0x00000010)
Jan 17 19:30:52 raspberrypi wpantund[428]: SpinelNCPTaskSendCommand.cpp:322: Requirement Failed ((mRetVal) == 0)
Jan 17 19:30:52 raspberrypi wpantund[428]: SendCommand task encountered an error: 16 (0x00000010)
Jan 17 19:34:35 raspberrypi wpantund[428]: wpantund[428]: SpinelNCPTaskSendCommand.cpp:322: Requirement Failed ((mRetVal) == 0)
Jan 17 19:34:35 raspberrypi wpantund[428]: wpantund[428]: SendCommand task encountered an error: 16 (0x00000010)
Jan 17 19:34:35 raspberrypi wpantund[428]: SpinelNCPTaskSendCommand.cpp:322: Requirement Failed ((mRetVal) == 0)
Jan 17 19:34:35 raspberrypi wpantund[428]: SendCommand task encountered an error: 16 (0x00000010)

```
Any Idea ?

**Comment by jwhui** [comment]
How did you build your NCP firmware?  Did you use the following command?
```bash
make -f examples/Makefile-efr32 TMF_PROXY=1 BORDER_ROUTER=1 COMMISSIONER=1
```

**Comment by jobroe** [comment]
I only added the joiner option, but before I tried it also without and it was not working as well.
`make -f examples/Makefile-efr32 TMF_PROXY=1 BORDER_ROUTER=1 JOINER=1 COMMISIONER=1`

**Comment by jwhui** [comment]
I believe adding `COMMISSIONER=1` will resolve the `PropertyNotFound` error.  Please try that again and report any errors you run into.

**Comment by jobroe** [comment]
As I mentioned it is enabled ...

**Comment by jwhui** [comment]
If you have the `COMMISSIONER=1` flag set, you should not see the `PropertyNotFound` error.  Double check that you have the commissioner feature enabled (note that you have a typo in your command above).

I just tried with the latest master and the command worked as expected.
```bash
$ sudo wpanctl commissioner -e
Commissioner command applied.
```

Note that the latest master does have a build issue with crypto acceleration, which is being addressed in #2487.

**Comment by jobroe** [comment]
Thanks, you are right the typo was really a issue.  But now I faced a different problem:
```
pi@raspberrypi:~ $ sudo wpanctl leave
Leaving current WPAN. . .
pi@raspberrypi:~ $ sudo wpanctl reset
Resetting NCP. . .
pi@raspberrypi:~ $ sudo wpanctl setprop Network:PANID 0xDEAD
pi@raspberrypi:~ $ sudo wpanctl setprop Network:XPANID DEAD1111DEAD2222
pi@raspberrypi:~ $ sudo wpanctl setprop Network:Key 11112233445566778899DEAD1111DEAD
pi@raspberrypi:~ $ sudo wpanctl config-gateway -d "fd11:22::"
Using prefix "fd11:22::"
Gateway configured.
pi@raspberrypi:~ $ sudo wpanctl form "OpenThreadGuide"
Forming WPAN "OpenThreadGuide" as node type "router"
Successfully formed!
pi@raspberrypi:~ $ sudo wpanctl commissioner -e
Commissioner command applied.
pi@raspberrypi:~ $ sudo wpanctl commissioner -a J01NU5 000b57fffebe5874
commissioner failed with error 4. InvalidForCurrentState

DIAGNOSIS: This error indicates that the device is not in a state where
it can complete your request, typically because a request is already in progress or
the NCP is already in the requested state.
If you are getting this error persistently, you should try reseting the network
settings on the NCP (via the "leave" command). The "status" command can be
helpful to further diagnose the issue.

pi@raspberrypi:~ $ sudo systemctl status wpantund.service 
● wpantund.service - wpantund
   Loaded: loaded (/etc/systemd/system/wpantund.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-01-17 19:37:07 UTC; 22h ago
 Main PID: 422 (wpantund)
   CGroup: /system.slice/wpantund.service
           └─422 /usr/sbin/wpantund -o Daemon:SetDefaultRouteForAutoAddedPrefix true -o IPv6:SetSLAACForAutoAddedPrefix true

Jan 18 18:04:41 raspberrypi wpantund[422]: wpantund[422]: State change: "offline" -> "associating"
Jan 18 18:04:41 raspberrypi wpantund[422]: State change: "offline" -> "associating"
Jan 18 18:04:43 raspberrypi wpantund[422]: wpantund[422]: State change: "associating" -> "associated"
Jan 18 18:04:43 raspberrypi wpantund[422]: wpantund[422]: Node type change: "unknown" -> "leader"
Jan 18 18:04:43 raspberrypi wpantund[422]: State change: "associating" -> "associated"
Jan 18 18:04:43 raspberrypi wpantund[422]: Node type change: "unknown" -> "leader"
Jan 18 18:05:36 raspberrypi wpantund[422]: wpantund[422]: SpinelNCPTaskSendCommand.cpp:322: Requirement Failed ((mRetVal) == 0)
Jan 18 18:05:36 raspberrypi wpantund[422]: wpantund[422]: SendCommand task encountered an error: 4 (0x00000004)
Jan 18 18:05:36 raspberrypi wpantund[422]: SpinelNCPTaskSendCommand.cpp:322: Requirement Failed ((mRetVal) == 0)
Jan 18 18:05:36 raspberrypi wpantund[422]: SendCommand task encountered an error: 4 (0x00000004)
```
As you see I tried to reset/leave the network, but it doesn't solve the issue. 
Any Idea ?  Thanks in advance

**Comment by jwhui** [comment]
I just tried on my setup and it works fine:

```bash
$ sudo wpanctl leave
Leaving current WPAN. . .
$ sudo wpanctl reset
Resetting NCP. . .
$ sudo wpanctl setprop Network:PANID 0xDEAD
$ sudo wpanctl setprop Network:XPANID DEAD1111DEAD2222
$ sudo wpanctl setprop Network:Key 11112233445566778899DEAD1111DEAD
$ sudo wpanctl config-gateway -d "fd11:22::"
Using prefix "fd11:22::"
Gateway configured.
$ sudo wpanctl form "OpenThreadGuide"
Forming WPAN "OpenThreadGuide" as node type "router"
Successfully formed!
$ sudo wpanctl commissioner -e
Commissioner command applied.
$ sudo wpanctl commissioner -a J01NU5 000b57fffebe5874
Joiner added.
```

How long are you waiting between the `commissioner -e` and `commissioner -a` commands?  Add a few seconds of delay there, if you haven't already, to see if that helps.

**Comment by jobroe** [comment]
A delay doesn't help.  I'm still I trying  to update my port ( Silabs Thunderboard Sense ) to the current master branch to obtain the crypto fixes.  The Problem is the UART doesn't work at all now. I saw you did the update of Gecko_SDK/RAIl , maybe you have an idea where to look to correct?

**Comment by jobroe** [comment]
Finally I got the my port working (although with the old uart driver but it's not a topic to discuss here) and the initial problem is solved. It seems the crypto acceleration issue  openthread/openthread#2487 was the reason. Thanks  !
